/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as landingRouteRouteImport } from './routes/(landing)/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as landingIndexRouteImport } from './routes/(landing)/index'
import { Route as DashboardCollectionRouteImport } from './routes/dashboard/$collection'
import { Route as DashboardTenantOverviewIndexRouteImport } from './routes/dashboard/tenant-overview/index'
import { Route as DashboardBldgAdminOverviewIndexRouteImport } from './routes/dashboard/bldg-admin-overview/index'
import { Route as DashboardBillsIndexRouteImport } from './routes/dashboard/bills/index'
import { Route as landingPropertiesIdRouteImport } from './routes/(landing)/properties.$id'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const landingRouteRoute = landingRouteRouteImport.update({
  id: '/(landing)',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const landingIndexRoute = landingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => landingRouteRoute,
} as any)
const DashboardCollectionRoute = DashboardCollectionRouteImport.update({
  id: '/$collection',
  path: '/$collection',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTenantOverviewIndexRoute =
  DashboardTenantOverviewIndexRouteImport.update({
    id: '/tenant-overview/',
    path: '/tenant-overview/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardBldgAdminOverviewIndexRoute =
  DashboardBldgAdminOverviewIndexRouteImport.update({
    id: '/bldg-admin-overview/',
    path: '/bldg-admin-overview/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardBillsIndexRoute = DashboardBillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const landingPropertiesIdRoute = landingPropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => landingRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof landingIndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/register': typeof RegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard/$collection': typeof DashboardCollectionRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/properties/$id': typeof landingPropertiesIdRoute
  '/dashboard/bills': typeof DashboardBillsIndexRoute
  '/dashboard/bldg-admin-overview': typeof DashboardBldgAdminOverviewIndexRoute
  '/dashboard/tenant-overview': typeof DashboardTenantOverviewIndexRoute
}
export interface FileRoutesByTo {
  '/register': typeof RegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard/$collection': typeof DashboardCollectionRoute
  '/': typeof landingIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/properties/$id': typeof landingPropertiesIdRoute
  '/dashboard/bills': typeof DashboardBillsIndexRoute
  '/dashboard/bldg-admin-overview': typeof DashboardBldgAdminOverviewIndexRoute
  '/dashboard/tenant-overview': typeof DashboardTenantOverviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(landing)': typeof landingRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/register': typeof RegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard/$collection': typeof DashboardCollectionRoute
  '/(landing)/': typeof landingIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/(landing)/properties/$id': typeof landingPropertiesIdRoute
  '/dashboard/bills/': typeof DashboardBillsIndexRoute
  '/dashboard/bldg-admin-overview/': typeof DashboardBldgAdminOverviewIndexRoute
  '/dashboard/tenant-overview/': typeof DashboardTenantOverviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/register'
    | '/verify-otp'
    | '/dashboard/$collection'
    | '/dashboard/'
    | '/properties/$id'
    | '/dashboard/bills'
    | '/dashboard/bldg-admin-overview'
    | '/dashboard/tenant-overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/register'
    | '/verify-otp'
    | '/dashboard/$collection'
    | '/'
    | '/dashboard'
    | '/properties/$id'
    | '/dashboard/bills'
    | '/dashboard/bldg-admin-overview'
    | '/dashboard/tenant-overview'
  id:
    | '__root__'
    | '/(landing)'
    | '/dashboard'
    | '/register'
    | '/verify-otp'
    | '/dashboard/$collection'
    | '/(landing)/'
    | '/dashboard/'
    | '/(landing)/properties/$id'
    | '/dashboard/bills/'
    | '/dashboard/bldg-admin-overview/'
    | '/dashboard/tenant-overview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  landingRouteRoute: typeof landingRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(landing)': {
      id: '/(landing)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof landingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(landing)/': {
      id: '/(landing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof landingIndexRouteImport
      parentRoute: typeof landingRouteRoute
    }
    '/dashboard/$collection': {
      id: '/dashboard/$collection'
      path: '/$collection'
      fullPath: '/dashboard/$collection'
      preLoaderRoute: typeof DashboardCollectionRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tenant-overview/': {
      id: '/dashboard/tenant-overview/'
      path: '/tenant-overview'
      fullPath: '/dashboard/tenant-overview'
      preLoaderRoute: typeof DashboardTenantOverviewIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/bldg-admin-overview/': {
      id: '/dashboard/bldg-admin-overview/'
      path: '/bldg-admin-overview'
      fullPath: '/dashboard/bldg-admin-overview'
      preLoaderRoute: typeof DashboardBldgAdminOverviewIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/bills/': {
      id: '/dashboard/bills/'
      path: '/bills'
      fullPath: '/dashboard/bills'
      preLoaderRoute: typeof DashboardBillsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(landing)/properties/$id': {
      id: '/(landing)/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof landingPropertiesIdRouteImport
      parentRoute: typeof landingRouteRoute
    }
  }
}

interface landingRouteRouteChildren {
  landingIndexRoute: typeof landingIndexRoute
  landingPropertiesIdRoute: typeof landingPropertiesIdRoute
}

const landingRouteRouteChildren: landingRouteRouteChildren = {
  landingIndexRoute: landingIndexRoute,
  landingPropertiesIdRoute: landingPropertiesIdRoute,
}

const landingRouteRouteWithChildren = landingRouteRoute._addFileChildren(
  landingRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardCollectionRoute: typeof DashboardCollectionRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBillsIndexRoute: typeof DashboardBillsIndexRoute
  DashboardBldgAdminOverviewIndexRoute: typeof DashboardBldgAdminOverviewIndexRoute
  DashboardTenantOverviewIndexRoute: typeof DashboardTenantOverviewIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCollectionRoute: DashboardCollectionRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBillsIndexRoute: DashboardBillsIndexRoute,
  DashboardBldgAdminOverviewIndexRoute: DashboardBldgAdminOverviewIndexRoute,
  DashboardTenantOverviewIndexRoute: DashboardTenantOverviewIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  landingRouteRoute: landingRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  RegisterRoute: RegisterRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
