/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTenantsIndexRouteImport } from './routes/dashboard/tenants/index'
import { Route as DashboardTenantOverviewIndexRouteImport } from './routes/dashboard/tenant-overview/index'
import { Route as DashboardTenanciesIndexRouteImport } from './routes/dashboard/tenancies/index'
import { Route as DashboardPropertiesIndexRouteImport } from './routes/dashboard/properties/index'
import { Route as DashboardPaymentsIndexRouteImport } from './routes/dashboard/payments/index'
import { Route as DashboardMaintenanceworkersIndexRouteImport } from './routes/dashboard/maintenanceworkers/index'
import { Route as DashboardMaintenancesIndexRouteImport } from './routes/dashboard/maintenances/index'
import { Route as DashboardInquiriesIndexRouteImport } from './routes/dashboard/inquiries/index'
import { Route as DashboardBldgAdminOverviewIndexRouteImport } from './routes/dashboard/bldg-admin-overview/index'
import { Route as DashboardBillingIndexRouteImport } from './routes/dashboard/billing/index'
import { Route as DashboardApartmentsIndexRouteImport } from './routes/dashboard/apartments/index'
import { Route as DashboardAnnouncementsIndexRouteImport } from './routes/dashboard/announcements/index'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTenantsIndexRoute = DashboardTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTenantOverviewIndexRoute =
  DashboardTenantOverviewIndexRouteImport.update({
    id: '/tenant-overview/',
    path: '/tenant-overview/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardTenanciesIndexRoute = DashboardTenanciesIndexRouteImport.update({
  id: '/tenancies/',
  path: '/tenancies/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPropertiesIndexRoute =
  DashboardPropertiesIndexRouteImport.update({
    id: '/properties/',
    path: '/properties/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPaymentsIndexRoute = DashboardPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMaintenanceworkersIndexRoute =
  DashboardMaintenanceworkersIndexRouteImport.update({
    id: '/maintenanceworkers/',
    path: '/maintenanceworkers/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardMaintenancesIndexRoute =
  DashboardMaintenancesIndexRouteImport.update({
    id: '/maintenances/',
    path: '/maintenances/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardInquiriesIndexRoute = DashboardInquiriesIndexRouteImport.update({
  id: '/inquiries/',
  path: '/inquiries/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBldgAdminOverviewIndexRoute =
  DashboardBldgAdminOverviewIndexRouteImport.update({
    id: '/bldg-admin-overview/',
    path: '/bldg-admin-overview/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardBillingIndexRoute = DashboardBillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardApartmentsIndexRoute =
  DashboardApartmentsIndexRouteImport.update({
    id: '/apartments/',
    path: '/apartments/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAnnouncementsIndexRoute =
  DashboardAnnouncementsIndexRouteImport.update({
    id: '/announcements/',
    path: '/announcements/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/register': typeof RegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsIndexRoute
  '/dashboard/apartments': typeof DashboardApartmentsIndexRoute
  '/dashboard/billing': typeof DashboardBillingIndexRoute
  '/dashboard/bldg-admin-overview': typeof DashboardBldgAdminOverviewIndexRoute
  '/dashboard/inquiries': typeof DashboardInquiriesIndexRoute
  '/dashboard/maintenances': typeof DashboardMaintenancesIndexRoute
  '/dashboard/maintenanceworkers': typeof DashboardMaintenanceworkersIndexRoute
  '/dashboard/payments': typeof DashboardPaymentsIndexRoute
  '/dashboard/properties': typeof DashboardPropertiesIndexRoute
  '/dashboard/tenancies': typeof DashboardTenanciesIndexRoute
  '/dashboard/tenant-overview': typeof DashboardTenantOverviewIndexRoute
  '/dashboard/tenants': typeof DashboardTenantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsIndexRoute
  '/dashboard/apartments': typeof DashboardApartmentsIndexRoute
  '/dashboard/billing': typeof DashboardBillingIndexRoute
  '/dashboard/bldg-admin-overview': typeof DashboardBldgAdminOverviewIndexRoute
  '/dashboard/inquiries': typeof DashboardInquiriesIndexRoute
  '/dashboard/maintenances': typeof DashboardMaintenancesIndexRoute
  '/dashboard/maintenanceworkers': typeof DashboardMaintenanceworkersIndexRoute
  '/dashboard/payments': typeof DashboardPaymentsIndexRoute
  '/dashboard/properties': typeof DashboardPropertiesIndexRoute
  '/dashboard/tenancies': typeof DashboardTenanciesIndexRoute
  '/dashboard/tenant-overview': typeof DashboardTenantOverviewIndexRoute
  '/dashboard/tenants': typeof DashboardTenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/register': typeof RegisterRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/announcements/': typeof DashboardAnnouncementsIndexRoute
  '/dashboard/apartments/': typeof DashboardApartmentsIndexRoute
  '/dashboard/billing/': typeof DashboardBillingIndexRoute
  '/dashboard/bldg-admin-overview/': typeof DashboardBldgAdminOverviewIndexRoute
  '/dashboard/inquiries/': typeof DashboardInquiriesIndexRoute
  '/dashboard/maintenances/': typeof DashboardMaintenancesIndexRoute
  '/dashboard/maintenanceworkers/': typeof DashboardMaintenanceworkersIndexRoute
  '/dashboard/payments/': typeof DashboardPaymentsIndexRoute
  '/dashboard/properties/': typeof DashboardPropertiesIndexRoute
  '/dashboard/tenancies/': typeof DashboardTenanciesIndexRoute
  '/dashboard/tenant-overview/': typeof DashboardTenantOverviewIndexRoute
  '/dashboard/tenants/': typeof DashboardTenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/register'
    | '/verify-otp'
    | '/dashboard/'
    | '/dashboard/announcements'
    | '/dashboard/apartments'
    | '/dashboard/billing'
    | '/dashboard/bldg-admin-overview'
    | '/dashboard/inquiries'
    | '/dashboard/maintenances'
    | '/dashboard/maintenanceworkers'
    | '/dashboard/payments'
    | '/dashboard/properties'
    | '/dashboard/tenancies'
    | '/dashboard/tenant-overview'
    | '/dashboard/tenants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/verify-otp'
    | '/dashboard'
    | '/dashboard/announcements'
    | '/dashboard/apartments'
    | '/dashboard/billing'
    | '/dashboard/bldg-admin-overview'
    | '/dashboard/inquiries'
    | '/dashboard/maintenances'
    | '/dashboard/maintenanceworkers'
    | '/dashboard/payments'
    | '/dashboard/properties'
    | '/dashboard/tenancies'
    | '/dashboard/tenant-overview'
    | '/dashboard/tenants'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/register'
    | '/verify-otp'
    | '/dashboard/'
    | '/dashboard/announcements/'
    | '/dashboard/apartments/'
    | '/dashboard/billing/'
    | '/dashboard/bldg-admin-overview/'
    | '/dashboard/inquiries/'
    | '/dashboard/maintenances/'
    | '/dashboard/maintenanceworkers/'
    | '/dashboard/payments/'
    | '/dashboard/properties/'
    | '/dashboard/tenancies/'
    | '/dashboard/tenant-overview/'
    | '/dashboard/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tenants/': {
      id: '/dashboard/tenants/'
      path: '/tenants'
      fullPath: '/dashboard/tenants'
      preLoaderRoute: typeof DashboardTenantsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tenant-overview/': {
      id: '/dashboard/tenant-overview/'
      path: '/tenant-overview'
      fullPath: '/dashboard/tenant-overview'
      preLoaderRoute: typeof DashboardTenantOverviewIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/tenancies/': {
      id: '/dashboard/tenancies/'
      path: '/tenancies'
      fullPath: '/dashboard/tenancies'
      preLoaderRoute: typeof DashboardTenanciesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/properties/': {
      id: '/dashboard/properties/'
      path: '/properties'
      fullPath: '/dashboard/properties'
      preLoaderRoute: typeof DashboardPropertiesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/payments/': {
      id: '/dashboard/payments/'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/maintenanceworkers/': {
      id: '/dashboard/maintenanceworkers/'
      path: '/maintenanceworkers'
      fullPath: '/dashboard/maintenanceworkers'
      preLoaderRoute: typeof DashboardMaintenanceworkersIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/maintenances/': {
      id: '/dashboard/maintenances/'
      path: '/maintenances'
      fullPath: '/dashboard/maintenances'
      preLoaderRoute: typeof DashboardMaintenancesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/inquiries/': {
      id: '/dashboard/inquiries/'
      path: '/inquiries'
      fullPath: '/dashboard/inquiries'
      preLoaderRoute: typeof DashboardInquiriesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/bldg-admin-overview/': {
      id: '/dashboard/bldg-admin-overview/'
      path: '/bldg-admin-overview'
      fullPath: '/dashboard/bldg-admin-overview'
      preLoaderRoute: typeof DashboardBldgAdminOverviewIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/billing/': {
      id: '/dashboard/billing/'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/apartments/': {
      id: '/dashboard/apartments/'
      path: '/apartments'
      fullPath: '/dashboard/apartments'
      preLoaderRoute: typeof DashboardApartmentsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/announcements/': {
      id: '/dashboard/announcements/'
      path: '/announcements'
      fullPath: '/dashboard/announcements'
      preLoaderRoute: typeof DashboardAnnouncementsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAnnouncementsIndexRoute: typeof DashboardAnnouncementsIndexRoute
  DashboardApartmentsIndexRoute: typeof DashboardApartmentsIndexRoute
  DashboardBillingIndexRoute: typeof DashboardBillingIndexRoute
  DashboardBldgAdminOverviewIndexRoute: typeof DashboardBldgAdminOverviewIndexRoute
  DashboardInquiriesIndexRoute: typeof DashboardInquiriesIndexRoute
  DashboardMaintenancesIndexRoute: typeof DashboardMaintenancesIndexRoute
  DashboardMaintenanceworkersIndexRoute: typeof DashboardMaintenanceworkersIndexRoute
  DashboardPaymentsIndexRoute: typeof DashboardPaymentsIndexRoute
  DashboardPropertiesIndexRoute: typeof DashboardPropertiesIndexRoute
  DashboardTenanciesIndexRoute: typeof DashboardTenanciesIndexRoute
  DashboardTenantOverviewIndexRoute: typeof DashboardTenantOverviewIndexRoute
  DashboardTenantsIndexRoute: typeof DashboardTenantsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAnnouncementsIndexRoute: DashboardAnnouncementsIndexRoute,
  DashboardApartmentsIndexRoute: DashboardApartmentsIndexRoute,
  DashboardBillingIndexRoute: DashboardBillingIndexRoute,
  DashboardBldgAdminOverviewIndexRoute: DashboardBldgAdminOverviewIndexRoute,
  DashboardInquiriesIndexRoute: DashboardInquiriesIndexRoute,
  DashboardMaintenancesIndexRoute: DashboardMaintenancesIndexRoute,
  DashboardMaintenanceworkersIndexRoute: DashboardMaintenanceworkersIndexRoute,
  DashboardPaymentsIndexRoute: DashboardPaymentsIndexRoute,
  DashboardPropertiesIndexRoute: DashboardPropertiesIndexRoute,
  DashboardTenanciesIndexRoute: DashboardTenanciesIndexRoute,
  DashboardTenantOverviewIndexRoute: DashboardTenantOverviewIndexRoute,
  DashboardTenantsIndexRoute: DashboardTenantsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  RegisterRoute: RegisterRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
